references #29, added metrics logic
deep-compute/basescript pull request #30
Opened 2017-01-20 13:52 UTC by algrebe

- stats abstraction for influxdb protocol and aggregation
- tests for stats
- updated travis to run tests
- updated basescript to periodically dump stats
- incremented version

closes #29 
connects to #29

2017-01-30 13:35 UTC, prashanthellina requested changes

2017-01-30 13:35 UTC, prashanthellina commented on basescript/basescript.py
> +    def define_basescript_metric_tags(self):
@algrebe Can we not call this function just `define_metric_tags`?

2017-02-02 12:25 UTC, algrebe commented on basescript/basescript.py
> +    def define_basescript_metric_tags(self):
@prashanthellina modified .

2017-02-04 15:03 UTC, prashanthellina approved these changes

2017-02-04 15:03 UTC, merged